# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'

target 'helpr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for helpr

  target 'helprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'helprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
